# Generated by Django 4.1.6 on 2023-02-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, verbose_name='사용자명')),
                ('userEmail', models.EmailField(max_length=32, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('signDate', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
            ],
        ),
    ]
