# Generated by Django 4.1.6 on 2023-02-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userEmail',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='userName',
            new_name='username',
        ),
    ]
