# Generated by Django 4.1.6 on 2023-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_rename_useremail_customer_useremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=300, verbose_name='비밀번호'),
        ),
    ]
