# Generated by Django 4.1.6 on 2023-02-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoondata',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
