# Generated by Django 4.1.6 on 2023-02-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_webtoondata_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webtoondata',
            name='link',
        ),
        migrations.AddField(
            model_name='webtoondata',
            name='title_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webtoondata',
            name='week',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='webtoondata',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
